docker_default_versions:
  xenial: "18.06.3~ce~3-0~ubuntu"
  bionic: "5:19.03.12~3-0~ubuntu-bionic"
  focal: "5:20.10.1~3-0~ubuntu-focal"
  buster: "5:20.10.6~3-0~debian-buster"
  bullseye: "5:24.0.6-1~debian.11~bullseye"
  bookworm: "5:24.0.6-1~debian.12~bookworm"